//! Loader for the committed Bot API spec snapshot.
//!
//! Every conformance test compares the crate against this snapshot rather than
//! against the live docs, so the suite is deterministic and runs offline. The
//! snapshot is generated by the `telegram-docs-setup` skill:
//!
//! ```text
//! python3 ~/.claude/skills/telegram-docs-setup/scripts/make_spec_snapshot.py \
//!     --tdocs tdocs --out crates/rustigram-types/tests/spec/bot-api-10.2.json
//! ```
//!
//! It is committed deliberately. A spec change should arrive as a reviewable
//! diff, not as a silent shift in what the tests believe.

#![allow(dead_code)] // each test binary uses a different subset

use std::collections::BTreeMap;

use serde::Deserialize;

/// The whole snapshot.
#[derive(Debug, Deserialize)]
pub struct Spec {
    pub snapshot_version: String,
    pub bot_api_version: String,
    pub bot_api_date: String,
    pub source_url: String,
    pub types: BTreeMap<String, SpecType>,
    pub methods: BTreeMap<String, SpecMethod>,
    /// Type name to the literal value of its `type`/`source`/`status` field.
    pub discriminants: BTreeMap<String, String>,
    /// Union base name to the list of type names that can inhabit it.
    pub unions: BTreeMap<String, Vec<String>>,
}

/// A field or parameter, stored as `["Integer", 0]` rather than an object.
///
/// The tuple form exists to keep the committed snapshot small: as objects it
/// was 13,700 lines, and the reviewable-diff argument for that is already served
/// better by the mirror's own `--check` drift report.
#[derive(Debug, Deserialize)]
pub struct SpecField(String, u8);

impl SpecField {
    /// The spec's own type text, e.g. `Integer` or `Array of PhotoSize`.
    pub fn kind(&self) -> &str {
        &self.0
    }

    pub fn optional(&self) -> bool {
        self.1 == 1
    }

    /// The element type, with any `Array of ` prefix removed.
    pub fn base_type(&self) -> &str {
        self.0.strip_prefix("Array of ").unwrap_or(&self.0)
    }
}

/// A spec type: its name maps straight to its field table.
pub type SpecType = BTreeMap<String, SpecField>;

/// A spec method: its name maps straight to its parameter table.
pub type SpecMethod = BTreeMap<String, SpecField>;

const SNAPSHOT: &str = include_str!("../spec/bot-api-10.2.json");

/// Loads the snapshot, panicking with a usable message if it is unreadable.
///
/// Failing loudly matters: a conformance suite that silently loads an empty
/// spec passes every test while checking nothing, which is worse than no suite
/// at all.
pub fn load() -> Spec {
    let spec: Spec = serde_json::from_str(SNAPSHOT).unwrap_or_else(|e| {
        panic!(
            "the committed spec snapshot failed to parse: {e}\n\
             Regenerate it with make_spec_snapshot.py — do not hand-edit it."
        )
    });
    assert!(
        !spec.types.is_empty() && !spec.methods.is_empty(),
        "the spec snapshot parsed but is empty; every conformance test would \
         vacuously pass. Regenerate it."
    );
    spec
}
